"""
Django settings for core project.

Generated by "django-admin startproject" using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import sys
from ..vendors.data import LANGUAGE_LIST
from decouple import config
from .paths import (
    BASE_DIR,
    TEMPLATES_DIR,
    CACHE_DIR,
    LOCALE_DIR,
    STATIC_DIR,
    MEDIA_DIR,
    URL_STATIC,
    URL_MEDIA,
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", "django-insecure-_o-49*6cn^&)d+^ea7%_!sryf^av-me7s%))6sur1*@aw$r#74")

# SECURITY WARNING: don"t run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)
TESTING = "test" in sys.argv

ALLOWED_HOSTS = [
    "127.0.0.1",
]

INTERNAL_IPS = [
    "127.0.0.1",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # apps
    "apps.account.apps.AccountConfig",
    "apps.cauth.apps.CauthConfig",
    "apps.page.apps.PageConfig",
    "apps.company.apps.CompanyConfig",
    "apps.error.apps.ErrorConfig",
    # extensions
]
if DEBUG and not TESTING:
    INSTALLED_APPS.append("debug_toolbar")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # apps
    "apps.company.middlewares.set_useragent_in_request_middleware",
    "apps.company.middlewares.set_locale_from_session_middleware",
]
if DEBUG and not TESTING:
    MIDDLEWARE = [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
        *MIDDLEWARE,
    ]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATES_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "company_test_db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

AVAILABLE_LANGUAGE_CODES = ["ru", "en"]

LANGUAGE_CODE = AVAILABLE_LANGUAGE_CODES[0]

LANGUAGES = [(lang.iso, lang.name) for lang in LANGUAGE_LIST if lang.iso in AVAILABLE_LANGUAGE_CODES]

LANGUAGE_COOKIE_NAME = "language"

SESSION_LANGUAGE_KEY = "current_language"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    LOCALE_DIR,
]

AVAILABLE_CURRENCY_CODES = ["RUB", "USD"]

CURRENCY_CODE = AVAILABLE_CURRENCY_CODES[0]

SESSION_CURRENCY_KEY = "current_currency"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = URL_STATIC

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_USER_MODEL = "account.Account"


LOGIN_URL = "cauth:login"

HOME_URL = "company:home"

